export const PERMISSIONS = {
  POST: {
    ADD_POST: "add_post",
    VIEW_ALL_POSTS: "view_all_posts",
    EDIT_POST: "edit_post",
    DELETE_POST: "delete_post",
    TOGGLE_ACTIVE_POST: "toggle_active_post",
    TOGGLE_FEATURED_POST: "toggle_featured_post",
  },
  CATEGORY: {
    ADD_CATEGORY: "add_category",
    VIEW_ALL_CATEGORIES: "view_all_categories",
    EDIT_CATEGORY: "edit_category",
    DELETE_CATEGORY: "delete_category",
    TOGGLE_ACTIVE_CATEGORY: "toggle_active_category",
    TOGGLE_FEATURED_CATEGORY: "toggle_featured_category",
    TOGGLE_DEFAULT_CATEGORY: "toggle_default_category",
  },
  NEWS: {
    ADD_NEWS_ARTICLE: "add_news_article",
    VIEW_ALL_NEWS_ARTICLES: "view_all_news_articles",
    EDIT_NEWS_ARTICLE: "edit_news_article",
    DELETE_NEWS_ARTICLE: "delete_news_article",
    TOGGLE_ACTIVE_NEWS_ARTICLE: "toggle_active_news_article",
    TOGGLE_FEATURED_NEWS_ARTICLE: "toggle_featured_news_article",
  },
  NEWS_CATEGORY: {
    ADD_NEWS_CATEGORY: "add_news_category",
    VIEW_ALL_NEWS_CATEGORIES: "view_all_news_categories",
    EDIT_NEWS_CATEGORY: "edit_news_category",
    DELETE_NEWS_CATEGORY: "delete_news_category",
    TOGGLE_ACTIVE_NEWS_CATEGORY: "toggle_active_news_category",
    TOGGLE_FEATURED_NEWS_CATEGORY: "toggle_featured_news_category",
    TOGGLE_DEFAULT_NEWS_CATEGORY: "toggle_default_news_category",
  },
  CONTACTS: {
    ADD_CONTACT: "add_contact",
    VIEW_ALL_CONTACTS: "view_all_contacts",
    VIEW_ALL_CONTACT_QUERIES: "view_all_contact_queries",
    EDIT_CONTACT: "edit_contact",
    DELETE_CONTACT: "delete_contact",
    DELETE_CONTACT_QUERY: "delete_contact_query",
    TOGGLE_ACTIVE_CONTACT: "toggle_active_contact",
    TOGGLE_ACTIVE_CONTACT_FORM: "toggle_active_contact_form",
    TOGGLE_FEATURED_CONTACT: "toggle_featured_contact",
  },
  TESTIMONIAL: {
    ADD_TESTIMONIAL: "add_testimonial",
    VIEW_ALL_TESTIMONIALS: "view_all_testimonials",
    EDIT_TESTIMONIAL: "edit_testimonial",
    DELETE_TESTIMONIAL: "delete_testimonial",
    TOGGLE_ACTIVE_TESTIMONIAL: "toggle_active_testimonial",
    TOGGLE_FEATURED_TESTIMONIAL: "toggle_featured_testimonial",
  },
  CAREER: {
    ADD_CAREER: "add_career",
    VIEW_ALL_CAREERS: "view_all_careers",
    EDIT_CAREER: "edit_career",
    DELETE_CAREER: "delete_career",
    TOGGLE_ACTIVE_CAREER: "toggle_active_career",
    TOGGLE_FEATURED_CAREER: "toggle_featured_career",
  },
  COURSES: {
    ADD_COURSE: "add_course",
    VIEW_ALL_COURSES: "view_all_courses",
    EDIT_COURSE: "edit_course",
    DELETE_COURSE: "delete_course",
    TOGGLE_ACTIVE_COURSE: "toggle_active_course",
    TOGGLE_FEATURED_COURSE: "toggle_featured_course",
  },
  PACKAGES: {
    ADD_PACKAGE: "add_package",
    VIEW_ALL_PACKAGES: "view_all_packages",
    EDIT_PACKAGE: "edit_package",
    DELETE_PACKAGE: "delete_package",
    TOGGLE_ACTIVE_PACKAGE: "toggle_active_package",
    TOGGLE_FEATURED_PACKAGE: "toggle_featured_package",
  },
  FILE: {
    ADD_FILE: "add_file",
    VIEW_ALL_FILES: "view_all_files",
    DELETE_FILE: "delete_file",
    DOWNLOAD_FILE: "download_file",
    TOGGLE_DEFAULT_FILE: "toggle_default_file",
    FILE_DETAILS: "file_details",
  },
  STAFF: {
    ADD_STAFF: "add_staff",
    VIEW_ALL_STAFFS: "view_all_staffs",
    EDIT_STAFF: "edit_staff",
    DELETE_STAFF: "delete_staff",
    ADD_STAFF_ROLE: "add_staff_role",
    VIEW_STAFF_ROLES: "view_staff_roles",
    EDIT_STAFF_ROLE: "edit_staff_role",
    DELETE_STAFF_ROLE: "delete_staff_role",
  },
  LANGUAGE: {
    ADD_LANGUAGE: "add_language",
    VIEW_ALL_LANGUAGES: "view_all_languages",
    EDIT_LANGUAGE: "edit_language",
    DELETE_LANGUAGE: "delete_language",
    TOGGLE_ACTIVE_LANGUAGE: "toggle_active_language",
    TOGGLE_RTL_LANGUAGE: "toggle_rtl_language",
    TOGGLE_DEFAULT_LANGUAGE: "toggle_default_language",
  },
  CMS_SETUP: {
    ADD_PAGE: "add_page",
    VIEW_ALL_PAGES: "view_all_pages",
    EDIT_PAGE: "edit_page",
    EDIT_PAGE_SECTIONS: "edit_page_sections",
    TOGGLE_ACTIVE_PAGE: "toggle_active_page",
  },
  WEBSITE_SETUP: {
    HEADER_SETUP: "header_setup",
    FOOTER_SETUP: "footer_setup",
    GENERAL_SETTINGS: "general_settings",
  },
  MENU_MANAGEMENT: {
    ADD_MENU: "add_menu",
    EDIT_MENU: "edit_menu",
    DELETE_MENU: "delete_menu",
    VIEW_ALL_MENUS: "view_all_menus",
    TOGGLE_PRODUCT_MENU: "toggle_product_menu",
    TOGGLE_ACTIVE_MENU: "toggle_active_menu",
  },
};
